/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { FunctionData, Swimlane, Activity, Initiative } from './types';

export const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
export const DETAIL_TABS = ['cs', 'km', 'inn', 'cm', 'eq'] as const;

export const FUNCTIONS: FunctionData[] = [
  {
    id: 'cs',
    label: 'Corporate Strategy',
    owner: 'Mohamed AlNaqeeb · Haya',
    color: 'var(--f-cs)',
    milestones: [
      { id: 'cs-m1', month: 1, label: 'Comms Plan Finalized', kpi: 'Awareness ≥85%', rag: 'g', key: true },
      { id: 'cs-m2', month: 2, label: 'Planning Cycle Handover', kpi: 'Strategy owns ≥80%', rag: 'g', key: false },
      { id: 'cs-m3', month: 2, label: 'SMMA Baseline Confirmed', kpi: 'Pre-assessment snapshot', rag: 'a', key: true },
      { id: 'cs-m4', month: 3, label: 'Strategy Launch Event', kpi: 'Satisfaction ≥85%', rag: 'g', key: true },
      { id: 'cs-m5', month: 3, label: 'Strategy Ownership Active', kpi: 'Joint planning ≥90%', rag: 'g', key: false },
      { id: 'cs-m6', month: 4, label: 'Awareness Workshops Done', kpi: '≥90% dept participation', rag: 'b', key: false },
      { id: 'cs-m7', month: 4, label: 'SMMA Assessment Done', kpi: 'BSC Compliance 95%', rag: 'b', key: true },
      { id: 'cs-m8', month: 5, label: 'Shared Reporting Room Live', kpi: '95% Reporting Accuracy', rag: 'b', key: false },
      { id: 'cs-m9', month: 9, label: 'BSC Full Ownership', kpi: '100% BSC owned', rag: 'b', key: true },
      { id: 'cs-m10', month: 11, label: 'Annual SMMA Review', kpi: 'Year-end benchmark', rag: 'b', key: false },
      { id: 'cs-m11', month: 11, label: 'Planning Transformation Done', kpi: 'Transformation complete', rag: 'b', key: true },
    ],
  },
  {
    id: 'km',
    label: 'Knowledge Management',
    owner: 'Maryam Alharbi · Mouza Yousef',
    color: 'var(--f-km)',
    milestones: [
      { id: 'km-m1', month: 2, label: 'KM Mapping Complete', kpi: '≥90% Metadata Accuracy', rag: 'b', key: true },
      { id: 'km-m2', month: 2, label: 'IT Inputs Submitted', kpi: 'Roles & Metadata to IT', rag: 'b', key: true },
      { id: 'km-m3', month: 2, label: 'Harvest Protocol Document', kpi: 'Protocol endorsed', rag: 'b', key: false },
      { id: 'km-m4', month: 5, label: 'KM Policy Package Endorsed', kpi: '≥50% adoption', rag: 'b', key: true },
      { id: 'km-m5', month: 5, label: 'Innovation Hub Café Live', kpi: '≥70% adoption', rag: 'b', key: false },
      { id: 'km-m6', month: 6, label: 'First Harvest Cycle', kpi: '≥2 harvest sessions', rag: 'b', key: true },
      { id: 'km-m7', month: 8, label: 'KM Dashboard Live', kpi: '≥90% on-time reporting', rag: 'b', key: true },
      { id: 'km-m8', month: 9, label: 'Expert Knowledge Transfer', kpi: 'Satisfaction ≥85%', rag: 'b', key: false },
      { id: 'km-m9', month: 11, label: 'Annual KM Report', kpi: 'Performance confirmed', rag: 'b', key: true },
    ],
  },
  {
    id: 'inn',
    label: 'Innovation & UAE Innovate',
    owner: 'Mouza Yousef · GELLIFY ME',
    color: 'var(--f-inn)',
    milestones: [
      { id: 'inn-m1', month: 1, label: 'Innovation Framework Endorsed', kpi: 'ISC/TEC compliance ≥90%', rag: 'g', key: true },
      { id: 'inn-m2', month: 2, label: 'Pipeline Baseline Set', kpi: '24 ideas migrated', rag: 'g', key: true },
      { id: 'inn-m3', month: 3, label: 'Innovation Cycle 2026 Launch', kpi: '≥15 high-quality ideas', rag: 'g', key: true },
      { id: 'inn-m4', month: 3, label: 'ADEK G9 Challenge Kick-off', kpi: 'Schools confirmed', rag: 'b', key: false },
      { id: 'inn-m5', month: 3, label: 'ADEK G11 Program Launch', kpi: 'G12 pathway set', rag: 'b', key: false },
      { id: 'inn-m6', month: 5, label: 'Cohort 2 Completed', kpi: 'Café satisfaction ≥90%', rag: 'b', key: true },
      { id: 'inn-m7', month: 6, label: 'Innovation Showcase Day', kpi: '≥90% satisfaction', rag: 'b', key: true },
      { id: 'inn-m8', month: 8, label: 'UAE Innovate Submission Pack', kpi: 'Package complete', rag: 'b', key: true },
      { id: 'inn-m9', month: 10, label: 'UAE Innovate 2026', kpi: 'Award targeted', rag: 'b', key: true },
      { id: 'inn-m10', month: 10, label: 'ADEK G11→UAE Innovate', kpi: 'Student submissions', rag: 'b', key: true },
    ],
  },
  {
    id: 'cm',
    label: 'Change Management',
    owner: 'Haya (via Faisal · Mouza · HR)',
    color: 'var(--f-cm)',
    milestones: [
      { id: 'cm-m1', month: 1, label: 'Governance Package Ready', kpi: 'Docs ready — no activation', rag: 'b', key: true },
      { id: 'cm-m2', month: 1, label: 'KPI Dashboard Live', kpi: 'KPIs defined', rag: 'b', key: false },
      { id: 'cm-m3', month: 2, label: 'Readiness Baseline Report', kpi: 'Heat map to Faisal', rag: 'b', key: true },
      { id: 'cm-m4', month: 2, label: 'Change Agents Onboarded', kpi: 'Via Ambassador network', rag: 'b', key: false },
      { id: 'cm-m5', month: 6, label: 'KM Portal Live', kpi: 'Utilisation tracked', rag: 'b', key: true },
      { id: 'cm-m6', month: 6, label: 'Governance Submitted', kpi: 'Conditional on Faisal', rag: 'b', key: true },
      { id: 'cm-m7', month: 6, label: 'Mid-term Review Report', kpi: 'To Faisal', rag: 'b', key: false },
      { id: 'cm-m8', month: 11, label: 'Year-End Report & BAU Handover', kpi: 'BAU docs complete', rag: 'b', key: true },
    ],
  },
  {
    id: 'eq',
    label: 'Excellence & Quality',
    owner: 'Mohamed Moustafa',
    color: 'var(--f-eq)',
    milestones: [
      { id: 'eq-m1', month: 0, label: 'ISO Documents Ready', kpi: 'Zero major NCs', rag: 'b', key: false },
      { id: 'eq-m2', month: 3, label: 'ISO Implementation Begins', kpi: 'ISO compliance ≥95%', rag: 'b', key: true },
      { id: 'eq-m3', month: 3, label: 'EFQM Self-Assessment', kpi: 'Evidence quality ≥90%', rag: 'b', key: true },
      { id: 'eq-m4', month: 5, label: 'Award Criteria Approved', kpi: 'Excellence model endorsed', rag: 'b', key: true },
      { id: 'eq-m5', month: 5, label: 'EFQM Assessment Report', kpi: 'Award calendar adherence', rag: 'b', key: false },
      { id: 'eq-m6', month: 8, label: 'ISO Audit Ready', kpi: 'Readiness ≥90%', rag: 'b', key: true },
      { id: 'eq-m7', month: 9, label: 'Excellence Cycle Launched', kpi: 'Participation ≥90%', rag: 'b', key: true },
      { id: 'eq-m8', month: 10, label: 'Governance Model Verified', kpi: 'Model embedded', rag: 'b', key: false },
      { id: 'eq-m9', month: 11, label: 'ISO Certification Achieved', kpi: 'Zero major NCs', rag: 'b', key: true },
    ],
  },
];

export const SWIMLANES: Record<string, Swimlane[]> = {
  cs: [
    { owner: 'Mohamed AlNaqeeb — Strategy Lead', color: 'var(--steel)', inits: ['1.1', '1.2', '1.3'] },
    { owner: 'Haya — Strategy Communications', color: 'var(--rose)', inits: ['1.4'] },
  ],
  km: [
    { owner: 'Mouza Yousef — KM Infrastructure', color: 'var(--cyan)', inits: ['3.1'] },
    { owner: 'Maryam Alharbi — KM Section Lead', color: 'var(--teal)', inits: ['3.2', '3.3', '3.4', '3.5'] },
  ],
  inn: [
    { owner: 'Mouza Yousef — Innovation Lead', color: 'var(--amber)', inits: ['2.1', '2.2', '2.3', '2.4'] },
  ],
  cm: [
    { owner: 'Haya — Change Management (Contacts: Faisal · Mouza · Maryam · Samuel · HR only)', color: 'var(--purple)', inits: ['INI-01', 'INI-02', 'INI-03', 'INI-05', 'INI-06'] },
  ],
  eq: [
    { owner: 'Mohamed Moustafa — Excellence & Quality Lead', color: 'var(--gold)', inits: ['4.1', '4.2', '4.3', '4.4'] },
  ],
};

export const INIT_COLORS: Record<string, Record<string, string>> = {
  cs: { '1.1': 'steel', '1.2': 'gold', '1.3': 'mint', '1.4': 'rose' },
  km: { '3.1': 'cyan', '3.2': 'teal', '3.3': 'emerald', '3.4': 'cobalt', '3.5': 'purple' },
  inn: { '2.1': 'steel', '2.2': 'amber', '2.3': 'mint', '2.4': 'rose' },
  cm: { 'INI-01': 'purple', 'INI-02': 'cobalt', 'INI-03': 'teal', 'INI-05': 'emerald', 'INI-06': 'gold' },
  eq: { '4.1': 'blue', '4.2': 'gold', '4.3': 'mint', '4.4': 'amber' },
};

export const INIT_THEMES: Record<string, Record<string, string>> = {
  cs: { '1.1': 't-blue', '1.2': 't-gold', '1.3': 't-mint', '1.4': 't-rose' },
  km: { '3.1': 't-cyan', '3.2': 't-teal', '3.3': 't-emerald', '3.4': 't-cobalt', '3.5': 't-purple' },
  inn: { '2.1': 't-blue', '2.2': 't-amber', '2.3': 't-mint', '2.4': 't-rose' },
  cm: { 'INI-01': 't-purple', 'INI-02': 't-cobalt', 'INI-03': 't-teal', 'INI-05': 't-emerald', 'INI-06': 't-gold' },
  eq: { '4.1': 't-blue', '4.2': 't-gold', '4.3': 't-mint', '4.4': 't-amber' },
};

export const DEFAULT_ACTIVITIES: Record<string, Activity[]> = {
  cs: [
    { id: 'cs-a1', init: '1.1', month: 0, type: 'activity', label: '📋 Develop Comms Plan', kpi: 'Awareness ≥85%', tooltip: 'Develop and execute Strategy Communication Plan', done: false, rag: 'b' },
    { id: 'cs-a2', init: '1.1', month: 1, type: 'deliverable', label: '📄 Comms Plan Finalized', kpi: 'Q1 deliverable', tooltip: 'Comms Plan finalized', done: false, rag: 'b' },
    { id: 'cs-a3', init: '1.1', month: 2, type: 'milestone', label: 'Workshops Begin', kpi: '', tooltip: 'Awareness Workshops begin org-wide', done: false, rag: 'b' },
    { id: 'cs-a4', init: '1.1', month: 3, type: 'activity', label: '🚀 Strategy Launch Event', kpi: 'Satisfaction ≥85%', tooltip: 'Conduct 2026 Strategy Launch Event', done: false, rag: 'b' },
    { id: 'cs-a5', init: '1.1', month: 4, type: 'activity', label: '🎓 Awareness Workshops', kpi: '≥90% dept participation', tooltip: 'Deliver Awareness Workshops org-wide', done: false, rag: 'b' },
    { id: 'cs-a6', init: '1.1', month: 4, type: 'milestone', label: 'Launch Closed', kpi: '', tooltip: 'Strategy Launch event concluded', done: false, rag: 'b' },
    { id: 'cs-a7', init: '1.1', month: 11, type: 'milestone', label: 'Awareness ≥85% Confirmed', kpi: '', tooltip: 'Full employee awareness validated', done: false, rag: 'b' },
    { id: 'cs-b1', init: '1.2', month: 0, type: 'activity', label: '🔄 Planning Cycle Handover', kpi: 'Strategy owns ≥80%', tooltip: 'Handover of Planning Cycle management', done: false, rag: 'b' },
    { id: 'cs-b2', init: '1.2', month: 2, type: 'milestone', label: 'Handover Complete', kpi: '', tooltip: 'Planning Cycle handover completed', done: false, rag: 'b' },
    { id: 'cs-b3', init: '1.2', month: 3, type: 'milestone', label: 'Strategy Ownership Active', kpi: '', tooltip: 'Strategy function has formal ownership', done: false, rag: 'b' },
    { id: 'cs-b4', init: '1.2', month: 7, type: 'activity', label: '🤝 Joint Planning w/ Perf.', kpi: 'Alignment ≥90%', tooltip: 'Execute Joint Planning with Performance team', done: false, rag: 'b' },
    { id: 'cs-b5', init: '1.2', month: 9, type: 'activity', label: '📊 BSC Full Ownership', kpi: '100% BSC owned', tooltip: 'Achieve complete BSC Process ownership', done: false, rag: 'b' },
    { id: 'cs-b6', init: '1.2', month: 10, type: 'deliverable', label: '📄 Planning Guidelines + KM', kpi: 'Oct–Dec deliverable', tooltip: 'Create Planning Guidelines with KM Support', done: false, rag: 'b' },
    { id: 'cs-b7', init: '1.2', month: 11, type: 'milestone', label: 'Transformation Closed', kpi: '', tooltip: 'Full transformation cycle complete', done: false, rag: 'b' },
    { id: 'cs-c1', init: '1.3', month: 0, type: 'activity', label: '📍 SMMA Baseline Doc', kpi: 'Pre-assessment snapshot', tooltip: 'Document current state across 8 SMMA dimensions', done: false, rag: 'b' },
    { id: 'cs-c2', init: '1.3', month: 2, type: 'milestone', label: 'Baseline Confirmed', kpi: '', tooltip: 'SMMA baseline documented and confirmed', done: false, rag: 'b' },
    { id: 'cs-c3', init: '1.3', month: 3, type: 'activity', label: '📈 SMMA Assessment', kpi: 'BSC Compliance 95%', tooltip: 'Plan and conduct SMMA assessment', done: false, rag: 'b' },
    { id: 'cs-c4', init: '1.3', month: 4, type: 'activity', label: '👥 SMMA Workshop', kpi: 'Leadership + cross-func', tooltip: 'Facilitated session with leadership across 8 dimensions', done: false, rag: 'b' },
    { id: 'cs-c5', init: '1.3', month: 4, type: 'activity', label: '🔍 Benchmarking Plan', kpi: 'Aligned to SMMA dims', tooltip: 'Develop and execute Benchmarking Plan', done: false, rag: 'b' },
    { id: 'cs-c6', init: '1.3', month: 5, type: 'deliverable', label: '📄 Shared Reporting Room', kpi: '95% Reporting Accuracy', tooltip: 'Establish Shared Reporting Room with Performance', done: false, rag: 'b' },
    { id: 'cs-c7', init: '1.3', month: 11, type: 'milestone', label: 'Annual SMMA Review', kpi: '', tooltip: 'Annual SMMA review completed', done: false, rag: 'b' },
    { id: 'cs-d1', init: '1.4', month: 0, type: 'activity', label: '📝 Comms Materials', kpi: 'Ready before Launch', tooltip: 'Develop all strategy communication materials', done: false, rag: 'b' },
    { id: 'cs-d2', init: '1.4', month: 2, type: 'deliverable', label: '📄 Materials Package', kpi: 'Q1 deliverable', tooltip: 'Materials package completed', done: false, rag: 'b' },
    { id: 'cs-d3', init: '1.4', month: 3, type: 'activity', label: '🚀 Support Launch Logistics', kpi: '≥90% dept participation', tooltip: 'Support Strategy Launch Event logistics', done: false, rag: 'b' },
    { id: 'cs-d4', init: '1.4', month: 4, type: 'activity', label: '🎓 Workshop Support', kpi: 'Employee awareness ≥85%', tooltip: 'Support org-wide strategy awareness workshops', done: false, rag: 'b' },
    { id: 'cs-d5', init: '1.4', month: 4, type: 'deliverable', label: '📊 Survey Deployed', kpi: 'Response rate ≥75%', tooltip: 'Deploy and analyze employee survey results', done: false, rag: 'b' },
  ],
  km: [
    { id: 'km-a1', init: '3.1', month: 0, type: 'activity', label: '📐 iFIKRA + AMPLIFY Alignment', kpi: 'Metadata model completed', tooltip: 'iFIKRA Expansion & AMPLIFY alignment', done: false, rag: 'b' },
    { id: 'km-a2', init: '3.1', month: 0, type: 'activity', label: '🗄 Collect Innovation Metadata', kpi: '≥90% Content Accuracy', tooltip: 'Collect & compile innovation metadata, templates', done: false, rag: 'b' },
    { id: 'km-a3', init: '3.1', month: 1, type: 'deliverable', label: '📄 Value Model Manuals', kpi: 'Q1-Q2 deliverable', tooltip: 'Value Model & Pitch Deck Manuals published', done: false, rag: 'b' },
    { id: 'km-a4', init: '3.1', month: 5, type: 'milestone', label: 'Innovation Hub Café Live', kpi: '≥70% Functional Adoption', tooltip: 'Launch open-access Innovation Hub Café', done: false, rag: 'b' },
    { id: 'km-b1', init: '3.2', month: 0, type: 'activity', label: '🗺 KM Mapping Begins', kpi: '≥90% Metadata Accuracy', tooltip: 'Complete Department-Level KM Mapping', done: false, rag: 'b' },
    { id: 'km-b2', init: '3.2', month: 2, type: 'milestone', label: 'KM Mapping Complete', kpi: '', tooltip: 'All department KM maps finalized', done: false, rag: 'b' },
    { id: 'km-b3', init: '3.2', month: 3, type: 'activity', label: '📋 KM Policies & Standards', kpi: '≥50% functional adoption', tooltip: 'Establish KM policies, standards & procedures', done: false, rag: 'b' },
    { id: 'km-b4', init: '3.2', month: 5, type: 'deliverable', label: '📄 KM Policy Package', kpi: 'Endorsed by leadership', tooltip: 'KM policy package published', done: false, rag: 'b' },
    { id: 'km-b5', init: '3.2', month: 6, type: 'activity', label: '🔗 Integrate KM Governance', kpi: 'Shared Archive ≥3 sessions', tooltip: 'Integrate KM with Innovation & Excellence', done: false, rag: 'b' },
    { id: 'km-b6', init: '3.2', month: 9, type: 'deliverable', label: '📄 KM Metrics Framework', kpi: '≥90% on-time reporting', tooltip: 'Create KM performance metrics & CI mechanisms', done: false, rag: 'b' },
    { id: 'km-c1', init: '3.3', month: 6, type: 'activity', label: '🎓 Awareness Sessions Program', kpi: 'Sessions >2/month', tooltip: 'Deliver Awareness Sessions & Capability Development', done: false, rag: 'b' },
    { id: 'km-c2', init: '3.3', month: 9, type: 'milestone', label: 'Expert-to-Practitioner Transfer', kpi: 'Satisfaction ≥85%', tooltip: 'Facilitate expert-to-practitioner knowledge transfer', done: false, rag: 'b' },
    { id: 'km-c3', init: '3.3', month: 11, type: 'milestone', label: 'Experts Forum Year-End', kpi: 'Dept repos ≥6', tooltip: 'Experts Forum annual wrap and continuous program', done: false, rag: 'b' },
    { id: 'km-d1', init: '3.4', month: 0, type: 'activity', label: '📊 Readiness Assessment', kpi: 'BRD approved', tooltip: 'KM Platform Readiness & Assessment Framework', done: false, rag: 'b' },
    { id: 'km-d2', init: '3.4', month: 2, type: 'milestone', label: 'IT Inputs Submitted', kpi: 'Roles & Metadata to IT', tooltip: 'Business inputs submitted to Samuel/IT', done: false, rag: 'b' },
    { id: 'km-d3', init: '3.4', month: 3, type: 'activity', label: '🔧 ISO KM Integration', kpi: 'KM mapping completed', tooltip: 'Integrate into ISO KM required acquaintance', done: false, rag: 'b' },
    { id: 'km-d4', init: '3.4', month: 6, type: 'activity', label: '⚙ Platform Implementation', kpi: 'KM dashboard launched', tooltip: 'Readiness & assessment implementation with IT', done: false, rag: 'b' },
    { id: 'km-d5', init: '3.4', month: 8, type: 'milestone', label: 'KM Dashboard Live', kpi: '≥90% on-time reporting', tooltip: 'KM platform dashboard launched and operational', done: false, rag: 'b' },
    { id: 'km-d6', init: '3.4', month: 9, type: 'activity', label: '🗺 Knowledge Discovery', kpi: '', tooltip: 'Knowledge discovery & mapping completion', done: false, rag: 'b' },
    { id: 'km-e1', init: '3.5', month: 1, type: 'activity', label: '📝 Protocol Design', kpi: 'Endorsed by Faisal', tooltip: 'Design Knowledge Harvest Protocol and templates', done: false, rag: 'b' },
    { id: 'km-e2', init: '3.5', month: 2, type: 'deliverable', label: '📄 Protocol Document', kpi: 'Q1 deliverable', tooltip: 'Knowledge Harvest Protocol Word doc finalized', done: false, rag: 'b' },
    { id: 'km-e3', init: '3.5', month: 6, type: 'milestone', label: 'Protocol Launch', kpi: 'First harvest cycle', tooltip: 'Launch Harvest Protocol and conduct first harvest', done: false, rag: 'b' },
    { id: 'km-e4', init: '3.5', month: 7, type: 'activity', label: '🌾 First Harvest Cycle', kpi: '≥2 sessions completed', tooltip: 'First structured knowledge harvest session', done: false, rag: 'b' },
    { id: 'km-e5', init: '3.5', month: 11, type: 'milestone', label: 'Annual KM Report', kpi: '', tooltip: 'Annual KM performance report completed', done: false, rag: 'b' },
  ],
  inn: [
    { id: 'in-a1', init: '2.1', month: 0, type: 'activity', label: '⚡ Activate ISC & TEC', kpi: 'ISC/TEC compliance ≥90%', tooltip: 'Activate ISC and TEC committees with clear mandates', done: false, rag: 'b' },
    { id: 'in-a2', init: '2.1', month: 0, type: 'activity', label: '📋 Review Innovation Framework', kpi: 'Framework endorsed', tooltip: 'Review, update & secure management endorsement', done: false, rag: 'b' },
    { id: 'in-a3', init: '2.1', month: 1, type: 'activity', label: '💰 Confirm Budget Mechanisms', kpi: 'Value Gate compliance ≥95%', tooltip: 'Confirm budget allocation for approved ideas', done: false, rag: 'b' },
    { id: 'in-a4', init: '2.1', month: 1, type: 'milestone', label: 'Framework Endorsed', kpi: '', tooltip: 'Innovation framework fully endorsed by management', done: false, rag: 'b' },
    { id: 'in-b1', init: '2.2', month: 0, type: 'activity', label: '📦 Migrate 24 Hackathon Ideas', kpi: '≥80% quality migration', tooltip: 'Migrate 24 refined Hackathon ideas into AMPLIFY', done: false, rag: 'b' },
    { id: 'in-b2', init: '2.2', month: 0, type: 'activity', label: '🔍 Activate AMPLIFY Ideas', kpi: '20 ideas assessed', tooltip: 'Integrate & assess 20 pre-existing AMPLIFY ideas', done: false, rag: 'b' },
    { id: 'in-b3', init: '2.2', month: 2, type: 'milestone', label: 'Pipeline Baseline Set', kpi: 'Readiness improvement ≥70%', tooltip: 'Full pipeline baseline established', done: false, rag: 'b' },
    { id: 'in-b4', init: '2.2', month: 3, type: 'activity', label: '🚀 Innovation Cycle 2026 Launch', kpi: '≥15 high-quality ideas', tooltip: 'Plan and deliver Innovation Cycle 2026', done: false, rag: 'b' },
    { id: 'in-b5', init: '2.2', month: 8, type: 'milestone', label: 'Cycle 2026 Showcase', kpi: 'Pipeline progressed', tooltip: 'Innovation Cycle 2026 mid-cycle showcase', done: false, rag: 'b' },
    { id: 'in-c1', init: '2.3', month: 3, type: 'activity', label: '💹 Finance Training (Ambassadors)', kpi: 'Competency +20%', tooltip: 'Ambassadors 2.0 Finance Training — ROI & Value Modeling', done: false, rag: 'b' },
    { id: 'in-c2', init: '2.3', month: 3, type: 'activity', label: '🎓 Cohort 2 — 5 Modules', kpi: 'Café satisfaction ≥90%', tooltip: 'GELLIFY ME Cohort 2: 5-Module Innovation Program', done: false, rag: 'b' },
    { id: 'in-c3', init: '2.3', month: 5, type: 'milestone', label: 'Cohort 2 Completed', kpi: '', tooltip: 'Cohort 2 all modules delivered', done: false, rag: 'b' },
    { id: 'in-d1', init: '2.4', month: 0, type: 'activity', label: '📣 Launch Comms Program', kpi: 'Engagement tracked', tooltip: 'Launch Innovation communication program', done: false, rag: 'b' },
    { id: 'in-d2', init: '2.4', month: 3, type: 'activity', label: '🎓 Graduate Hackathon (KU×TQT)', kpi: '≥15 submissions', tooltip: 'Launch Graduate Hackathon Program KU × TQT', done: false, rag: 'b' },
    { id: 'in-d3', init: '2.4', month: 2, type: 'activity', label: '🏫 ADEK G9 Challenge Kick-off', kpi: 'Schools confirmed', tooltip: 'ADEK/STEM Challenge Cycle 2 — G9 Stream kick-off', done: false, rag: 'b' },
    { id: 'in-d4', init: '2.4', month: 3, type: 'activity', label: '🏫 ADEK G11 Program Launch', kpi: 'Problem themes selected', tooltip: 'ADEK G11 mentorship & idea development program', done: false, rag: 'b' },
    { id: 'in-d5', init: '2.4', month: 5, type: 'activity', label: '🏢 Cross-OpCo Interactions', kpi: 'TAQA Dist. & Water engaged', tooltip: 'Cross-OpCo gallery walks and discussion circles', done: false, rag: 'b' },
    { id: 'in-d6', init: '2.4', month: 6, type: 'activity', label: '🌟 Innovation Showcase Day', kpi: '≥90% satisfaction', tooltip: 'TQT Innovation Showcase Day — internal mid-year', done: false, rag: 'b' },
    { id: 'in-d7', init: '2.4', month: 7, type: 'activity', label: '🏫 ADEK G11 Idea Development', kpi: 'G12 pathway set', tooltip: 'G11 students develop ideas for G12 UAE Innovate', done: false, rag: 'b' },
    { id: 'in-d8', init: '2.4', month: 8, type: 'activity', label: '📦 UAE Innovate Packaging', kpi: 'Submission package Oct', tooltip: 'UAE Innovate 2026 submission packaging', done: false, rag: 'b' },
    { id: 'in-d9', init: '2.4', month: 10, type: 'milestone', label: 'UAE Innovate 2026', kpi: 'Award targeted', tooltip: 'UAE Innovate 2026 — submission and participation', done: false, rag: 'b' },
    { id: 'in-d10', init: '2.4', month: 10, type: 'milestone', label: 'ADEK G11→UAE Innovate', kpi: 'Student submissions', tooltip: 'ADEK G11 students submit to UAE Innovate', done: false, rag: 'b' },
  ],
  cm: [
    { id: 'cm-a1', init: 'INI-01', month: 0, type: 'activity', label: '📋 Draft ToR & RACI', kpi: 'Docs ready — no activation', tooltip: 'Draft Change Governance ToR, RACI — no activation until confirmed', done: false, rag: 'b' },
    { id: 'cm-a2', init: 'INI-01', month: 1, type: 'deliverable', label: '📄 Governance Package Ready', kpi: 'Reviewed by Faisal', tooltip: 'Full governance package — ToR, RACI, PPM gate, templates', done: false, rag: 'b' },
    { id: 'cm-a3', init: 'INI-01', month: 6, type: 'milestone', label: 'Governance Submitted', kpi: 'Conditional on Faisal', tooltip: 'Present governance package for approval — conditional milestone', done: false, rag: 'b' },
    { id: 'cm-b1', init: 'INI-02', month: 0, type: 'activity', label: '📊 Design Readiness Survey', kpi: 'Response rate ≥75%', tooltip: 'Design survey — delivered via Ambassadors through Mouza', done: false, rag: 'b' },
    { id: 'cm-b2', init: 'INI-02', month: 1, type: 'activity', label: '📡 Deploy & Collect Data', kpi: 'Data via Ambassadors', tooltip: 'Deploy survey through Ambassador network (via Mouza)', done: false, rag: 'b' },
    { id: 'cm-b3', init: 'INI-02', month: 2, type: 'deliverable', label: '📄 Heat Map & Baseline Report', kpi: 'Delivered to Faisal', tooltip: 'Readiness heat map and baseline report completed', done: false, rag: 'b' },
    { id: 'cm-c1', init: 'INI-03', month: 1, type: 'activity', label: '🤝 Map Change Agents via Mouza', kpi: '≥1 agent per directorate', tooltip: 'Map & onboard Change Agents through Ambassador network via Mouza', done: false, rag: 'b' },
    { id: 'cm-c2', init: 'INI-03', month: 2, type: 'milestone', label: 'Change Agents Onboarded', kpi: 'Ambassador path only', tooltip: 'Change Agent network established via Ambassadors', done: false, rag: 'b' },
    { id: 'cm-c3', init: 'INI-03', month: 3, type: 'activity', label: '🎓 Capability Building Workshops', kpi: 'Training completion ≥90%', tooltip: 'Change Agent capability building workshops — internal only', done: false, rag: 'b' },
    { id: 'cm-c4', init: 'INI-03', month: 5, type: 'milestone', label: 'Network Activated', kpi: '', tooltip: 'Change Agent network fully operational', done: false, rag: 'b' },
    { id: 'cm-e1', init: 'INI-05', month: 3, type: 'activity', label: '🗺 Content Taxonomy + LL Template', kpi: 'LL template published', tooltip: 'KM content taxonomy and Lessons Learned template — Maryam', done: false, rag: 'b' },
    { id: 'cm-e2', init: 'INI-05', month: 6, type: 'milestone', label: 'KM Portal Live', kpi: 'Utilisation tracked', tooltip: 'KM Portal launched with CM content — via Samuel', done: false, rag: 'b' },
    { id: 'cm-e3', init: 'INI-05', month: 11, type: 'activity', label: '📊 Quarterly Utilisation Reports', kpi: '≥70% LL template use', tooltip: 'Ongoing KM Portal utilisation reports (quarterly)', done: false, rag: 'b' },
    { id: 'cm-f1', init: 'INI-06', month: 0, type: 'activity', label: '📐 KPI Dictionary & Dashboard', kpi: 'Dashboard live', tooltip: 'Build KPI dictionary & performance dashboard — Samuel', done: false, rag: 'b' },
    { id: 'cm-f2', init: 'INI-06', month: 1, type: 'milestone', label: 'Dashboard Live', kpi: 'KPIs defined', tooltip: 'Performance dashboard operational', done: false, rag: 'b' },
    { id: 'cm-f3', init: 'INI-06', month: 3, type: 'deliverable', label: '📄 Q1 Performance Report', kpi: 'Delivered on time', tooltip: 'Q1 KPI review and variance analysis', done: false, rag: 'b' },
    { id: 'cm-f4', init: 'INI-06', month: 6, type: 'activity', label: '🔍 Mid-term Review', kpi: 'Report to Faisal', tooltip: 'Mid-term change program review against baseline', done: false, rag: 'b' },
    { id: 'cm-f5', init: 'INI-06', month: 11, type: 'deliverable', label: '📄 Year-End Report & BAU Handover', kpi: 'BAU docs complete', tooltip: 'End-of-year performance report & BAU handover package', done: false, rag: 'b' },
  ],
  eq: [
    { id: 'eq-a1', init: '4.1', month: 0, type: 'activity', label: '🏛 Develop Governance Model', kpi: 'Zero Overdue Findings', tooltip: 'Develop internal audit governance model', done: false, rag: 'b' },
    { id: 'eq-a2', init: '4.1', month: 1, type: 'deliverable', label: '📄 Monitoring Templates', kpi: 'IA Follow-up on time', tooltip: 'Develop monitoring and follow-up templates', done: false, rag: 'b' },
    { id: 'eq-a3', init: '4.1', month: 6, type: 'activity', label: '⚙ Facilitate Audit Lifecycle', kpi: 'Zero overdue findings', tooltip: 'Coordinate and facilitate internal audit lifecycle', done: false, rag: 'b' },
    { id: 'eq-a4', init: '4.1', month: 10, type: 'milestone', label: 'Governance Model Verified', kpi: 'Model embedded', tooltip: 'Implement governance model and verify results', done: false, rag: 'b' },
    { id: 'eq-b1', init: '4.2', month: 0, type: 'activity', label: '🏆 Develop Award Criteria', kpi: 'Excellence model endorsed', tooltip: 'Develop TQT Internal Award Criteria', done: false, rag: 'b' },
    { id: 'eq-b2', init: '4.2', month: 3, type: 'activity', label: '🔍 Review Criteria w/ Teams', kpi: 'Participation ≥90%', tooltip: 'Review criteria and verify with cross-functional teams', done: false, rag: 'b' },
    { id: 'eq-b3', init: '4.2', month: 5, type: 'deliverable', label: '📄 Criteria Approved', kpi: '', tooltip: 'Criteria approved — awareness campaign begins', done: false, rag: 'b' },
    { id: 'eq-b4', init: '4.2', month: 6, type: 'activity', label: '📣 Awareness Campaign', kpi: 'Integration ≥90%', tooltip: 'Get approval and start awareness campaign', done: false, rag: 'b' },
    { id: 'eq-b5', init: '4.2', month: 9, type: 'milestone', label: 'Excellence Cycle Launched', kpi: 'Participation ≥90%', tooltip: 'Launch internal excellence evaluation cycle', done: false, rag: 'b' },
    { id: 'eq-c1', init: '4.3', month: 0, type: 'activity', label: '📅 Awards Participation Plan', kpi: 'Criteria clarity ≥90%', tooltip: 'Develop & implement awards participation plan', done: false, rag: 'b' },
    { id: 'eq-c2', init: '4.3', month: 3, type: 'activity', label: '📊 EFQM Self-Assessment', kpi: 'Evidence quality ≥90%', tooltip: 'Conduct EFQM Self-Assessment', done: false, rag: 'b' },
    { id: 'eq-c3', init: '4.3', month: 5, type: 'deliverable', label: '📄 EFQM Assessment Report', kpi: 'Award calendar adherence', tooltip: 'EFQM self-assessment report completed', done: false, rag: 'b' },
    { id: 'eq-c4', init: '4.3', month: 6, type: 'activity', label: '⬆ Implement EFQM Improvements', kpi: 'Cross-func engagement >90%', tooltip: 'Implement EFQM improvement plan', done: false, rag: 'b' },
    { id: 'eq-c5', init: '4.3', month: 9, type: 'activity', label: '🎓 EFQM Training Delivery', kpi: 'All TQT functions covered', tooltip: 'Implement EFQM Training across TQT', done: false, rag: 'b' },
    { id: 'eq-d1', init: '4.4', month: 0, type: 'activity', label: '📋 ISO Documents & Templates', kpi: 'Zero major NCs', tooltip: 'Preparation of basic ISO documents and templates', done: false, rag: 'b' },
    { id: 'eq-d2', init: '4.4', month: 1, type: 'milestone', label: 'ISO Documents Ready', kpi: 'ISO compliance ≥95%', tooltip: 'All basic ISO documents and templates prepared', done: false, rag: 'b' },
    { id: 'eq-d3', init: '4.4', month: 3, type: 'activity', label: '⚙ ISO Implementation', kpi: 'Zero major NCs', tooltip: 'Implement ISO standards and requirements', done: false, rag: 'b' },
    { id: 'eq-d4', init: '4.4', month: 6, type: 'activity', label: '🔍 Internal Audit & Gap Review', kpi: 'Readiness ≥90%', tooltip: 'Internal audit, gap assessment & management review', done: false, rag: 'b' },
    { id: 'eq-d5', init: '4.4', month: 8, type: 'milestone', label: 'ISO Audit Ready', kpi: '', tooltip: 'Initial audit gap assessment confirmed ready', done: false, rag: 'b' },
    { id: 'eq-d6', init: '4.4', month: 11, type: 'milestone', label: '✅ Certification Achieved', kpi: 'Zero major NCs', tooltip: 'ISO Certification Audit — compliance confirmed', done: false, rag: 'b' },
  ],
};

export const DEFAULT_INITIATIVES: Record<string, Initiative[]> = {
  cs: [
    { id: '1.1', title: 'Strategy Communication & Launch', owner: 'AlNaqeeb', rag: 'g' },
    { id: '1.2', title: 'Planning Cycle Transformation', owner: 'AlNaqeeb', rag: 'g' },
    { id: '1.3', title: 'Strategy Maturity & Performance', owner: 'AlNaqeeb', rag: 'a' },
    { id: '1.4', title: 'Strategy Communication Pack', owner: 'Haya', rag: 'g' },
  ],
  km: [
    { id: '3.1', title: 'Knowledge Infrastructure & Platform', owner: 'Mouza', rag: 'b' },
    { id: '3.2', title: 'KM Governance & Org. Learning', owner: 'Maryam', rag: 'b' },
    { id: '3.3', title: 'Experts Forum & Capability Building', owner: 'Maryam', rag: 'b' },
    { id: '3.4', title: 'KM Platform Delivery', owner: 'Maryam', rag: 'b' },
    { id: '3.5', title: 'Knowledge Harvest Protocol', owner: 'Maryam', rag: 'b' },
  ],
  inn: [
    { id: '2.1', title: 'Innovation Governance & Framework', owner: 'Mouza', rag: 'g' },
    { id: '2.2', title: 'Innovation Pipeline Acceleration', owner: 'Mouza', rag: 'g' },
    { id: '2.3', title: 'Capability & Culture Development', owner: 'Mouza', rag: 'b' },
    { id: '2.4', title: 'Engagement & Ecosystem Building', owner: 'Mouza', rag: 'g' },
  ],
  cm: [
    { id: 'INI-01', title: 'Change Governance Structure', owner: 'Haya', rag: 'b' },
    { id: 'INI-02', title: 'Organisational Readiness Assessment', owner: 'Haya', rag: 'b' },
    { id: 'INI-03', title: 'Change Agent & Ambassador Network', owner: 'Haya', rag: 'b' },
    { id: 'INI-05', title: 'KM Integration', owner: 'Haya', rag: 'b' },
    { id: 'INI-06', title: 'Performance Measurement & Reporting', owner: 'Haya', rag: 'b' },
  ],
  eq: [
    { id: '4.1', title: 'TAQA Internal Governance & Follow-up', owner: 'Moustafa', rag: 'b' },
    { id: '4.2', title: 'Internal Excellence Framework', owner: 'Moustafa', rag: 'b' },
    { id: '4.3', title: 'External Awards & Recognition', owner: 'Moustafa', rag: 'b' },
    { id: '4.4', title: 'ISO Compliance & Standards Mgmt.', owner: 'Moustafa', rag: 'b' },
  ],
};
